#!/bin/sh

case `uname -s` in
    FreeBSD)
    aclocal19
    autoheader259
    automake19 --add-missing --foreign --copy
    autoconf259
    ;;

    *)
    aclocal
    autoheader
    automake --add-missing --foreign --copy
    autoconf
    ;;
esac
